repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0 #v1.105.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c #v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
