---
name: "Lock or Stale"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Stale:
    uses: gucio1200/gh-workflows/.github/workflows/general_stale.yml@v7.7.4
    secrets: inherit

  Lock:
    needs: Stale
    uses: gucio1200/gh-workflows/.github/workflows/general_lock.yml@v7.7.4
    secrets: inherit
