---
name: "TF Docs"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.tpl'
      - '**/*.tmpl'
      - '**/*.py'
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  Docs:
    uses: gucio1200/gh-workflows/.github/workflows/terraform_gen-doc.yml@v6.1.2
    secrets: inherit
