---
name: "Linters"

on:
  pull_request:

jobs:
  action-lint:
    name: GH Action Lint
    uses: gucio1200/gh-workflows/.github/workflows/linter_gh-action.yml@v7.1.6

  yaml-lint:
    name: Yaml Lint
    uses: gucio1200/gh-workflows/.github/workflows/linter_yaml.yml@v7.1.6
